<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <UserSecretsId>dotnet-SOFIManagerWS-2b27a629-87f2-41ad-a7ee-79def213e601</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SwaggerDark.css" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SwaggerDark.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.1" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>
</Project>
